[project]
name = "bareASGI-static"
version = "5.0.0-alpha.0"
description = "Static file support for bareASGI"
authors = [
    { name = "Rob Blackbourn", email = "rob.blackbourn@gmail.com" }
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
]
readme = "README.md"
dependencies = [
    "aiofiles>=0.7,<1",
    "bareASGI>=5.0.0-alpha.4,<6"
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "pytest-runner",
    "pylint",
    "types-aiofiles"
]
docs = [
    "mkdocs>=1.2,<2",
    "mkdocs-material>=7.2,<8",
    "jetblack-markdown>=0.6,<1",
    "mike>=1.1.1,<2"
]
examples = [
    "hypercorn>=0.11,<1",
    "uvloop>=0.15,<1",
    "uvicorn>=0.15.0,<1"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://bareASGI.github.io/bareASGI-static"
Repository = "https://github.com/bareASGI/bareASGI-static"
Issues = "https://github.com/bareASGI/bareASGI-static/issues"

# pylint
[tool.pylint.main]
py-version = "3.12"
jobs = 4

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_"]
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]

[tool.pylint."messages control"]
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "use-implicit-booleaness-not-comparison-to-string",
    "use-implicit-booleaness-not-comparison-to-zero",
    "missing-module-docstring",
]

# pytest
[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "function"

# mypy
[tool.mypy]
files = [ "src", "tests", "examples" ]

[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true
